---
- name: nginx
  package: name=nginx-mainline
- name: fancyindex
  become: no
  git:
    repo: https://aur.archlinux.org/nginx-mainline-mod-fancyindex.git
    dest: "{{ pacaur }}/nginx-mainline-mod-fancyindex"
- name: nginx.conf
  copy:
    dest: /etc/nginx/nginx.conf
    content: |
      load_module /usr/lib/nginx/modules/ngx_http_fancyindex_module.so;
      events {}

      http {
        include mime.types;
        sendfile on;

      server {
        listen 8080;
        location / {
          return 301 https://$host$uri;
        }
      }

      server {
        listen 443 ssl http2;
        ssl_certificate      /etc/letsencrypt/live/{{ domain }}/fullchain.pem;
        ssl_certificate_key  /etc/letsencrypt/live/{{ domain }}/privkey.pem;
        root {{ public }};
        fancyindex on;
        fancyindex_default_sort date_desc;
        fancyindex_exact_size off;
        fancyindex_name_length 1000;
        fancyindex_localtime on;
        fancyindex_time_format "%Y-%m-%d %H:%M";
      
        location ~ ^/(Music|Videos) {
          auth_basic "hello";
          auth_basic_user_file dmca;
        }
      }
      }
...
