[package]
name = "luser"
version = "0.1.0"
authors = ["Hoàng Đức Hiếu <hdhoang@hdhoang.space>"]

[dependencies]
scraper = "*"
hyper = "*"
regex = "*"
quick-xml = "*"
rustc-serialize = "*"

[dependencies.irc]
git = "https://github.com/aatxe/irc"
