edition = "2021"
fn_params_layout = "Vertical"
newline_style = "unix"
reorder_imports = true
use_field_init_shorthand = true
use_try_shorthand = true

# unstable:
# version = "Two"
# format_code_in_doc_comments = true
# format_macro_bodies = true
# format_macro_matchers = true
# format_strings = true
# group_imports = "StdExternalCrate"
# imports_granularity = "One"
# imports_layout = "Vertical"
# normalize_doc_attributes = true
# overflow_delimited_expr = true
# trailing_comma = "Vertical"
# wrap_comments = true
