#!/usr/bin/python

from PyQt4 import QtCore, QtDBus

CONNMAN_SERVICE = "net.connman"
CONNMAN_PATH    = "/"
CONNMAN_IFACE   = "net.connman.Manager"
app = QtCore.QCoreApplication([''])

class Dummy(QtCore.QObject):
      @QtCore.pyqtSlot(str, QtDBus.QDBusVariant)
      def exit_when_connected(self, name, value):
            if name == "State" and value.variant() in ["ready", "online"]:
                  app.quit()
obj = Dummy()

bus = QtDBus.QDBusConnection.systemBus()
bus.connect(CONNMAN_SERVICE,
            CONNMAN_PATH,
            CONNMAN_IFACE,
            "PropertyChanged",
            obj.exit_when_connected)

app.exec_()
