- ini_file: dest=/etc/systemd/journald.conf section=Journal option=Storage value=volatile
- name: packages
  pacman: name={{item}}
  with_items:
    - acpi
    - acpid
    - breeze-kde4
    - cantata
    - chromaprint
    - chromium
    - dhclient
    - dolphin
    - drkonqi
    - emacs-pkgbuild-mode
    - firefox
    - gwenview
    - ibus-anthy
    - ibus-qt
    - ibus-unikey
    - kdegraphics-ksnapshot
    - kdegraphics-okular
    - kdemultimedia-kmix
    - kwallet-pam
    - lib32-alsa-plugins
    - lib32-libcanberra-pulse
    - lib32-mpg123
    - lib32-sni-qt
    - libva-intel-driver
    - mesa-libgl
    - mpc
    - mpd
    - mpv
    - picard
    - plasma-desktop
    - plasma-nm
    - powertop
    - pulseaudio-alsa
    - qemu
    - qt5-wayland
    - rust
    - sddm
    - skype
    - sni-qt
    - steam
    - syncthing
    - ttf-hannom
    - ttf-inconsolata
    - ttf-linux-libertine
    - virtualbox-guest-iso
    - virtualbox-host-dkms
    - wine
    - wireshark-gtk
    - wpa_supplicant
    - xf86-input-libinput
    - xf86-input-wacom
    - xf86-video-intel
    - xorg-server
    - xorg-server-xwayland
    - xorg-xinput
    - yakuake
- user: name={{user}} append=yes groups=wireshark
- ini_file: dest=/etc/NetworkManager/NetworkManager.conf section=main option=dhcp value=internal
- copy: src=keyboard.conf dest=/etc/X11/xorg.conf.d/
- copy: src=pointer.conf dest=/etc/X11/xorg.conf.d/
- template: src=rotation-button dest=/etc/acpi/events/
- service: name=acpid state=started enabled=yes
- command: rustc --out-dir /usr/local/bin {{h}}/bin/rotate-screen.rs creates=/usr/local/bin/rotate-screen
- copy: src=powercfg dest=/usr/local/bin/ mode=0744
- copy: src=powercfg.service dest=/etc/systemd/system/
- service: name=powercfg state=started enabled=yes
