#!/bin/bash
set -euo pipefail

SYSEXT="${1}"
URL="https://extensions.fcos.fr/extensions"
sudo-rs install -d -m 0755 -o 0 -g 0 /etc/sysupdate.${SYSEXT}.d
sudo-rs restorecon -RFv /etc/sysupdate.${SYSEXT}.d
static-curl --silent --fail --location "${URL}/${SYSEXT}.conf" \
  | sudo-rs tee "/etc/sysupdate.${SYSEXT}.d/${SYSEXT}.transfer"
sudo-rs /usr/lib/systemd/systemd-sysupdate update --component "${SYSEXT}"
