#!/bin/env fish
set fish_trace 1

# this helps with iphone CTIA TRRS arrangement, where Left+Right channels cancel each other out
# https://apple.stackexchange.com/a/135972

# changing output/stream balance in pavucontrol is another hack, but
# balance restored when using vol+/- keys. And by this way the sound
# is richer

set apps 'mpv|Firefox'

for channel in $(pw-link --input . playback_FL)
    for app in (string split '|' $apps)
        pw-link --disconnect $app:output_FL $channel
    end

end
for channel in $(pw-link --input . playback_FR)
    for app in (string split '|' $apps)
        pw-link $app:output_FL $channel &
    end
end
wait
pw-link --verbose --links . playback_FR
