#!/bin/env python3
# -*- apheleia-formatter: dprint -*-
import sys

# protocol: https://github.com/inputusername/rescrobbled?tab=readme-ov-file#configuration
# player-whitelist = ["mpv"]
# filter-script = ",scrobble-filter"

submit = True
artist, title, album, _genres = (l.rstrip() for l in sys.stdin.readlines())

EXTENSIONS = [
    ".alac",
    ".flac",
    ".m3u8",
    ".m4a",
    ".mp3",
    ".mp4",
    ".ogg",
    ".opus",
    ".smk",
]
if (artist == "" and album == "" and title == "") or any(
    title.lower().endswith(e) for e in EXTENSIONS
):
    # if "-" in title:
    #     artist, title = title.rsplit("-", maxsplit=1)
    # else:
    submit = False
    sys.exit(0)

COMPILATIONS = ["buddy.vn", ".", "Music"]
COMPILERS = [
    "Francisco Callahan",
    "Hà Nội Vi Vu",
    "VTV - Bài Ca Đi Cùng Năm Tháng",
    "VTV SHOWS",
]
FLIP_COMPILERS = [
    "ogafroman",
    "Vietnam War Song Project",
]
ARTIST_REPLACE_RULES = {
    "": [" OFFICIAL", " Official"],
    "Bích Liên": ["NSƯT Bích Liên"],
    "Buckethead": ["Bucketheadland"],
    "Frédéric Chopin": ["Fryderyk Chopin"],
    "Johann Sebastian Bach": ["Netherlands Bach Society"],
    "Khánh Ly": ["Ca Sĩ KHÁNH LY"],
    "Megadriver": ["megadriver"],
    "Microwave": ["Microwave band", "MICROWAVE"],
    "Minh Thu": ["MINH THU"],
    "Mỹ Tâm": ["My Tam"],
}
ARTISTS = ARTIST_REPLACE_RULES.keys()

TITLE_REPLACE_RULES = {
    "": [
        " OFFICIAL MUSIC VIDEO",
        " Official Lyrics Video",
        " OFFICIAL LYRICS VIDEO",
        " (OFFICIAL AUDIO)",
    ],
}

if album in COMPILATIONS:
    album = ""

if artist in FLIP_COMPILERS and " - " in title:
    artist, title = title.rsplit(" - ", maxsplit=1)
if artist in COMPILERS and " - " in title:
    title, artist = title.rsplit(" - ", maxsplit=1)
    if title in ARTISTS:
        artist, title = title, artist

for replacement, matches in ARTIST_REPLACE_RULES.items():
    for s in matches:
        artist = artist.replace(s, replacement, count=1)

for replacement, matches in TITLE_REPLACE_RULES.items():
    for s in matches:
        title = title.replace(s, replacement, count=1)

artist = artist.strip()
album = album.strip()
title = title.strip()

print(
    f"""
  artist           : {artist}
    album          : {album}
     title         : {title}
""",
    end="\n\n",
    flush=True,
    file=sys.stderr,
)

if submit:
    print(artist, title, album, sep="\n")
