[alias]
i = "auditable install --profile dist"
iu = "auditable install-update -g -a -d -i"

[build]
# fedora: from cargo, to install do env RUSTC_WRAPPER= cargo...
rustc-wrapper = "sccache"
jobs = -1
rustflags = ["-C", "target-cpu=native"]

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
  # verify with `readelf -p .comment`
  "-C",
  "link-arg=--ld-path=mold",
  "-C",
  "target-cpu=native",
]

[profile.dist]
# from cargo-dist
inherits = "release"
lto = "thin"
# https://nnethercote.github.io/perf-book/build-configuration.html
strip = "debuginfo"

[profile.profiling]
inherits = "release"
debug = true
