[unstable]
script = true
# unknown native-completions = true

avoid-dev-deps = true
gc = true
no-embed-metadata = true

codegen-backend = true
trim-paths = true

gitoxide = true
[unstable.git]
shallow-index = true
shallow-deps = true

[alias]
i = "auditable install --locked --profile dist"
iu = "auditable install-update --git --all --jobs 1 --downdate --allow-no-update"

[resolver]
incompatible-rust-versions = "fallback"

[build]
jobs = -2
rustflags = [
  # verify with `readelf -p .comment`
  "-Clinker=clang",
  "-Clink-arg=--ld-path=wild",
  # "-Clink-arg=-Wl,--no-rosegment",
  "-Cforce-frame-pointers=yes",
  "-Ctarget-cpu=native",
]
target-dir = "build"

[profile.dist]
# from cargo-dist
inherits = "release"
lto = "thin"
# https://nnethercote.github.io/perf-book/build-configuration.html
strip = "debuginfo"
trim-paths = ["diagnostics", "object"]

[profile.profiling]
inherits = "release"
debug = "full"
trim-paths = ["diagnostics", "object"]

[profile.dev]
debug = "none"
codegen-backend = "cranelift"
trim-paths = ["diagnostics", "object"]

[profile.test]
codegen-backend = "cranelift"
trim-paths = ["diagnostics", "object"]
