# -*- mode: toml -*-
[storage]
driver = "overlay"
# https://github.com/containers/podman/blob/main/docs/tutorials/performance.md
[storage.options.overlay]
mount_program = "/bin/fuse-overlayfs"
[storage.options.pull_options]
enable_partial_images = "true"
use_hard_links = "false"
