[user]
name = "hdhoang"
email = "code@hdhoang.space"

[ui]
default-command = "diff"

editor = "emacsclient -c"
merge-editor = "mergiraf"

[ui.diff]
tool = ["difft", "--color=always", "$left", "$right"]

[git]
# https://jj-vcs.github.io/jj/latest/config/#set-of-private-commits
private-commits = "description(glob:'wip:*') | description(glob:'private:*')"
subprocess = false
