[user]
name = "hdhoang"
email = "code@hdhoang.space"

[ui]
default-command = "log"
default-description = "\n\nSigned-off-by: Hoang Duc Hieu <code@hdhoang.space>\n"

diff.tool = ["difft", "--color=always", "$left", "$right"]
editor = "emacsclient -c"
