set unstable # for --fmt
set shell := ["nu", "-m", "light", "-c"]

default:
    just --list

start:
    bash -x ~/homes/config/start.sh

up:
    # tool sync
    flatpak -u update -y
    cargo iu
    sudo-rs dnf --setopt=install_weak_deps=False upgrade -y

sway_tree PATTERN:
    swaymsg -t get_tree -r|rg -i {{ PATTERN }}

mu PATH:
    mpv --no-resume-playback --vo=null --no-video --no-ytdl --replaygain=track --scripts=gh/mpv-mpris/mpris.so --shuffle --playlist=rclone-cache --playlist={{ PATH }} --volume=44

yt *SUB:
    -mkdir -v ~/rclone-cache/{{ SUB }}; cd ~/rclone-cache/{{ SUB }} ; yt-dlp --format 250/251/140/hls-400/vorbis/bestaudio --prefer-free-formats --download-archive ~/yta.txt --cookies ~/ytc.txt -a ~/q.org --no-mtime --embed-metadata --playlist-random --compat-options filename-sanitization
    cd ~/rclone-cache/{{ SUB }} ; /bin/rename --verbose webm opus *.webm

[no-cd]
cl repo:
    jj git clone --colocate {{ repo }}

[no-cd]
t *params:
    cargo nextest run {{ params }}

[no-cd]
d *paths:
    try { jj diff {{ paths }} err> /dev/null } catch { git diff -- {{ paths }} err> /dev/null }
