set unstable := true
set shell := ["nu", "-m", "light", "-c"]

set dotenv-required
set dotenv-path := "homes/config/env.conf"

default:
    just --list

start:
    ~/homes/config/start.sh

sway_tree PATTERN:
    swaymsg -t get_tree -r|rg -i {{ PATTERN }}

mu PATH:
    coreutils mkdir -p rclone-cache
    mpv --no-resume-playback --no-ytdl \
        --vo=null --no-video \
        --load-console=no --load-select=no \
        --display-tags-append='SYNOPSIS' \
        --display-tags-append='REPLAYGAIN_REFERENCE_LOUDNESS' \
        --display-tags-append='purl' \
        --script-opts=stats-redraw_delay=13 \
        --scripts=run/mpv-mpris2.so \
        --shuffle ./rclone-cache/ --playlist={{ PATH }} \
        --volume=100 --replaygain=track \
        --prefetch-playlist=yes \
        --cache=yes --cache-pause-wait=30 --cache-pause-initial=yes

[working-directory('rclone-cache/cp')]
yt:
    #!/bin/env fish
    yt-dlp --format=250/251/140/hls-400/vorbis/aac-hi/bestaudio \
        --remux-video='mkv>opus/webm>opus' --prefer-free-formats \
        --download-archive ~/yta.txt --cookies ~/ytc.txt -a ~/q.org \
        --no-mtime --parse-metadata='%(format)s %(format_id)s:%(meta_format)s' --embed-metadata \
        --playlist-random --compat-options=filename-sanitization --output="%(uploader)s/%(title)s [%(id)s].%(ext)s" \
        --exec=after_video:'sleep %(upload_date>%d|2)q' \
        --color=stderr:always 2>| tee /dev/fd/2 | rg -m1 --color=always 'PO.Token|not.a.bot|again.later'
    rsgain easy --preset=ebur128 --skip-existing -m 3 .
    org.musicbrainz.Picard .//
    # rclone copy --fast-list -P --transfers=1 --skip-links --exclude='*.part' ./// cp:

[no-cd]
cl repo:
    jj git clone --colocate {{ repo }}

[no-cd]
t *params:
    cargo nextest run {{ params }}

[no-cd]
d *paths:
    try { jj diff {{ paths }} err> /dev/null } catch { git diff -- {{ paths }} err> /dev/null }
