- mount: src=LABEL=var name=/var fstype=auto state=present
- mount: src=LABEL=hdhoang name={{home}} fstype=auto state=present
- name: network
  ini_file: dest=/etc/systemd/network/eth0.network section={{item.s}} option={{item.o}} value={{item.v}}
  with_items:
    - {s: Match, o: Name, v: eth0}
    - {s: Network, o: Address, v: "{{address}}/24"}
    - {s: Network, o: Gateway, v: "{{network}}.1"}
    - {s: Network, o: IPForward, v: "yes"}
- lineinfile: dest=/etc/resolv.conf line="nameserver {{ network }}.1"
- service: name=systemd-networkd state=started enabled=yes
- lineinfile: dest=/etc/ssh/sshd_config line="ChallengeResponseAuthentication yes"
- copy: src={{ansible_hostname}}/leds dest=/usr/local/bin/ mode=744
- copy: src={{ansible_hostname}}/leds.service dest=/etc/systemd/system/
- service: name=leds state=started enabled=yes
