# Installation directory for all the tools:
store_directory = "$HOME/run"

[rclone] # selfupdate
owner = "rclone"
repo = "rclone"
asset_name.linux = "linux-amd64.zip"
asset_name.windows = "windows-amd64"
[gphotosdl] # selfupdate
owner = "rclone"
repo = "gphotosdl"
asset_name.linux = "x_x"
asset_name.windows = "s_x"

# glyphs
[babelstone]
owner = "babelstone"
repo = "babelstonehan-ufo"
exe_name = "BabelStoneHan-Basic.ttf"
asset_name.linux = "Basic"
asset_name.windows = "Basic"
[babelstone-extra]
owner = "babelstone"
repo = "babelstonehan-ufo"
exe_name = "BabelStoneHan-Extra.ttf"
asset_name.linux = "Extra"
asset_name.windows = "Extra"

# pagers
[bat]
[difftastic]
[starship]
[tspin]
owner = "bensadeh"
repo = "tailspin"
exe_name = "tspin"
asset_name.linux = "_64-unknown-linux-musl"
[hl]
owner = "pamburus"
repo = "hl"
asset_name.linux = "_64-musl"
asset_name.windows = "s.zip"
[delta]
owner = "dandavison"
repo = "delta"
asset_name.linux = "_64-unknown-linux-gnu"
asset_name.windows = "_64-pc-windows-msvc"
[wezterm]
owner = "wez"
repo = "wezterm"
asset_name.linux = "-Ubuntu20.04.AppImage"
[zellij]
owner = "zellij-org"
repo = "zellij"
asset_name.linux = "_64-u"
[fish]
owner = "fish-shell"
repo = "fish-shell"
exe_name = "fish"
asset_name.linux = "d64"
[coreutils]
owner = "uutils"
repo = "coreutils"
asset_name.linux = "_64-unknown-linux-gnu"
asset_name.windows = "_64-pc-windows-gnu.zip"
[findutils]
owner = "uutils"
repo = "findutils"
exe_name = "find"
asset_name.linux = "x-g"
asset_name.windows = "_64-pc-windows-gnu.zip"
[diffutils]
owner = "uutils"
repo = "diffutils"
asset_name.linux = "_64-unknown-linux-gnu"
asset_name.windows = "_64-pc-windows-gnu.zip"
[nu]
owner = "nushell"
repo = "nushell"
exe_name = "nu"
asset_name.linux = "_64-unknown-linux-musl"
asset_name.windows = "_64-pc-windows-msvc.zip"
[hexyl]
owner = "sharkdp"
repo = "hexyl"
asset_name.linux = "_64-unknown-linux-gnu"
asset_name.windows = "_64-pc-windows-msvc.zip"
[hextazy]
owner = "0xfalafel"
repo = "hextazy"
asset_name.linux = "hextazy"
[imhex]
owner = "WerWolv"
repo = "ImHex"
asset_name.linux = "_64.A"
[binsider]
owner = "orhun"
repo = "binsider"
asset_name.linux = "_64-unknown-linux-gnu"
asset_name.windows = "windows"
[rustdesk]
owner = "rustdesk"
repo = "rustdesk"
asset_name.linux = "_64.AppImage"
asset_name.windows = "_64.exe"
[rainfrog]
owner = "achristmascarl"
repo = "rainfrog"
asset_name.linux = "_64-unknown-linux-gnu"
asset_name.windows = "_64-pc-windows-msvc.zip"
[glance]
owner = "glanceapp"
repo = "glance"
asset_name.linux = "x-am"
asset_name.windows = "s-am"
[crawl]
owner = "crawl"
repo = "crawl"
exe_name = "crawl-tiles"
asset_name.linux = "tiles.x"
[httm]
owner = "kimono-koans"
repo = "httm"
asset_name.linux = "stripped"
[rama]
owner = "plabayo"
repo = "rama"
asset_name.linux = "_64-u"

# dashboards
[procs]
[eza]
owner = "eza-community"
repo = "eza"
asset_name.linux = "_64-unknown-linux-musl.t"
[btdu]
owner = "CyberShadow"
repo = "btdu"
asset_name.linux = "_64"
[broot]
owner = "Canop"
repo = "broot"
# asset_name.linux = "zip" # x86_64-linux/broot
asset_name.windows = "zip" # x86_64-pc-windows-gnu/broot.exe
[dua]
owner = "Byron"
repo = "dua-cli"
exe_name = "dua"
asset_name.linux = "_64-unknown-linux-musl"
asset_name.windows = "ws"
[trippy]
owner = "fujiapple852"
repo = "trippy"
exe_name = "trip"
asset_name.linux = "_64-unknown-linux-musl.tar"
asset_name.windows = "_64-pc-windows-msvc"
[rustscan]
owner = "RustScan"
repo = "RustScan"
exe_name = "rustscan"
asset_name.linux = "_64-linux.zip"
asset_name.windows = "exe"
[netscanner]
owner = "Chleba"
repo = "netscanner"
asset_name.linux = "_64"
[bandwhich]
owner = "imsnif"
repo = "bandwhich"
asset_name.linux = "_64-unknown-linux-m"
asset_name.windows = "ws"
[oryx]
owner = "pythops"
repo = "oryx"
asset_name.linux = "_64"
[processwatch]
owner = "intel"
repo = "processwatch"
asset_name.linux = "w"
[bottom]
owner = "ClementTsang"
repo = "bottom"
exe_name = "btm"
asset_name.linux = "_64-unknown-linux-musl"
asset_name.windows = "_64-pc-windows-msvc"
[mprocs]
owner = "pvolok"
repo = "mprocs"
asset_name.windows = "windows"
asset_name.linux = "linux"
[cyme]
owner = "tuna-f1sh"
repo = "cyme"
asset_name.linux = "_64-unknown"
asset_name.windows = "ws"
[otel-cli]
owner = "equinix-labs"
repo = "otel-cli"
asset_name.linux = "x_amd64.t"
[Dorion]
owner = "SpikeHD"
repo = "Dorion"
asset_name.linux = "d64_portable"
asset_name.windows = "n64_portable"
[chdig]
owner = "azat"
repo = "chdig"
asset_name.linux = "t-x86_64.tar.g"
asset_name.windows = "zip"
[samply]
owner = "mstange"
repo = "samply"
asset_name.linux = "x-m"
asset_name.windows = "zip"
[flamelens]
owner = "YS-L"
repo = "flamelens"
asset_name.linux = "_64-unknown-linux-gnu"
asset_name.windows = "zip"
[keepassxc]
owner = "keepassxreboot"
repo = "keepassxc"
asset_name.linux = "A"
[tsui]
owner = "neuralinkcorp"
repo = "tsui"
asset_name.linux = "x-x"

# history wrangling
[topgrade]
owner = "topgrade-rs"
repo = "topgrade"
asset_name.linux = "_64-unknown-linux-musl"
asset_name.windows = "_64-pc-windows-msvc"
[just]
owner = "casey"
repo = "just"
asset_name.linux = "_64-unknown-linux-musl"
asset_name.windows = "_64-pc-windows-msvc"
[jj]
owner = "jj-vcs"
repo = "jj"
asset_name.linux = "_64-unknown-linux-musl"
# ended at 0.29 asset_name.windows = "_64-pc-windows-msvc"
[gg]
owner = "gulbanana"
repo = "gg"
asset_name.linux = "App"
asset_name.windows = "exe"

# k8s
[k9s]
[kubetui]
owner = "sarub0b0"
repo = "kubetui"
asset_name.linux = "_64-unknown-linux-musl"
[kdash]
owner = "kdash-rs"
repo = "kdash"
asset_name.linux = "linux.tar"
[regctl]
owner = "regclient"
repo = "regclient"
exe_name = "regctl"
asset_name.linux = "regctl-linux-amd64"
[cilium-cli]
owner = "cilium"
repo = "cilium-cli"
exe_name = "cilium"
asset_name.linux = "linux-amd64"
# [helm]
# has checksums only
# owner = "helm"
# repo = "helm"
# asset_name.linux = "linux-amd64.tar"
[pwru]
owner = "cilium"
repo = "pwru"
asset_name.linux = "d64"
[umoci]
owner = "opencontainers"
repo = "umoci"
asset_name.linux = "d64"

# search & destroy
[fd]
[sd]
owner = "chmln"
repo = "sd"
asset_name.linux = "_64-unknown-linux-musl"
asset_name.windows = "_64-pc-windows-msvc"
[f2]
owner = "ayoisaiah"
repo = "f2"
asset_name.linux = "x_amd64.t"
asset_name.windows = "4.z"
[ripgrep]
[ripgrep-all]
owner = "phiresky"
repo = "ripgrep-all"
exe_name = "rga"
asset_name.linux = "musl"
asset_name.windows = "msvc"
[gitleaks]
owner = "gitleaks"
repo = "gitleaks"
asset_name.linux = "x_x64"
[comby]
owner = "comby-tools"
repo = "comby"
exe_name = "comby"
asset_name.linux = "tar"
[ast-grep]
owner = "ast-grep"
repo = "ast-grep"
asset_name.linux = "_64-unknown-linux"
asset_name.windows = "_64-p"
[srgn]
owner = "alexpovel"
repo = "srgn"
asset_name.linux = "linux"
asset_name.windows = "windows"
[kdl-lsp]
owner = "kdl-org"
repo = "kdl-rs"
exe_name = "kdl-lsp"
asset_name.linux = "_64-u"
asset_name.windows = "_64-p"
[hyperfine]
owner = "sharkdp"
repo = "hyperfine"
asset_name.linux = "_64-unknown-linux-g"
asset_name.windows = "_64-p"
[mdq]
owner = "yshavit"
repo = "mdq"
asset_name.linux = "x-x64."
asset_name.windows = "ws"
[qsv] # --update
owner = "dathere"
repo = "qsv"
exe_name = "qsvp"
asset_name.linux = "_64-unknown-linux-g"
[fq]
owner = "wader"
repo = "fq"
asset_name.linux = "x_amd"
asset_name.windows = "ws"
[yq]
owner = "mikefarah"
repo = "yq"
asset_name.linux = "x_amd64.t"
asset_name.windows = "d64.e"
[jaq]
owner = "01mf02"
repo = "jaq"
asset_name.linux = "_64-unknown-linux-gnu"
asset_name.windows = "_64-p"
[vector]
owner = "vectordotdev"
repo = "vector"
asset_name.linux = "_64-unknown-linux-gnu"
asset_name.windows = "_64-p"
[drivel]
owner = "hgrsd"
repo = "drivel"
asset_name.linux = "_64-unknown-linux-gnu"
[quickwit]
owner = "quickwit-oss"
repo = "quickwit"
asset_name.linux = "_64-unknown-linux-gnu"
[krokiet]
owner = "qarmin"
repo = "czkawka"
exe_name = "krokiet"
asset_name.linux = "t_gui_heif_libraw"
asset_name.windows = "t.e"
[cargo-machete]
owner = "bnjbvr"
repo = "cargo-machete"
asset_name.linux = "musl"
[cargo-insta]
owner = "mitsuhiko"
repo = "insta"
exe_name = "cargo-insta"
asset_name.linux = "x-g"
[cargo-audit]
owner = "rustsec"
repo = "rustsec"
exe_name = "cargo-audit"
asset_name.linux = "x-m"
[duckdb]
owner = "duckdb"
repo = "duckdb"
asset_name.linux = "i-linux-amd64.z"
asset_name.windows = "i-windows-am"
[litefs]
owner = "superfly"
repo = "litefs"
asset_name.linux = "am"

# formatters
[biff]
owner = "BurntSushi"
repo = "biff"
asset_name.linux = "_64-u"
asset_name.windows = "_64-p"
[jxl-oxide]
owner = "tirr-c"
repo = "jxl-oxide"
asset_name.linux = "_64-u"
asset_name.windows = "_64-p"
[dprint] # upgrade then config update
owner = "dprint"
repo = "dprint"
asset_name.linux = "_64-unknown-linux-gnu"
asset_name.windows = "c.zip"
[rsgain]
owner = "complexlogic"
repo = "rsgain"
asset_name.linux = "L"
asset_name.windows = "win"
[fpcalc]
owner = "acoustid"
repo = "chromaprint"
exe_name = "fpcalc"
asset_name.windows = "ws-x"
asset_name.linux = "x-x"
[picard]
owner = "metabrainz"
repo = "picard"
asset_name.windows = "d-2.13.3.e"
[shellcheck]
owner = "koalaman"
repo = "shellcheck"
asset_name.linux = "x.x"
asset_name.windows = "zip"
[shfmt]
owner = "patrickvane"
repo = "shfmt"
asset_name.linux = "linux_amd64"
asset_name.windows = "64.exe"
# b3sum: use `coreutils b3sum`
[xxhsum]
owner = "Cyan4973"
repo = "xxHash"
asset_name.windows = "zip"
[minidump-stackwalk]
owner = "rust-minidump"
repo = "rust-minidump"
exe_name = "minidump-stackwalk"
[atuin]
owner = "atuinsh"
repo = "atuin"
asset_name.linux = "_64-unknown-linux-gnu.t"
[recast]
owner = "Altair-Bueno"
repo = "recast"
asset_name.linux = "_64-u"
asset_name.windows = "_64-p"
[offline-scrobbler]
owner = "theirix"
repo = "offline-scrobbler"
asset_name.linux = "x-m"
[mpv-mpris2]
owner = "eNV25"
repo = "mpv-mpris2"
exe_name = "mpv-mpris2.so"
asset_name.linux = "s"
[rescrobbled]
owner = "InputUserName"
repo = "rescrobbled"
asset_name.linux = "s"

# builders
[sccache]
owner = "mozilla"
repo = "sccache"
asset_name.linux = "e-v0.9.1-x86_64-u"
asset_name.windows = "e-v0.9.1-x86_64-p"
[nextest] # self update
owner = "nextest-rs"
repo = "nextest"
exe_name = "cargo-nextest"
asset_name.linux = "_64-unknown-linux"
asset_name.windows = "_64-pc-windows-msvc.zip"
[cargo-dist]
owner = "axodotdev"
repo = "cargo-dist"
exe_name = "dist"
asset_name.linux = "_64-unknown-linux-musl"
asset_name.windows = "_64-p"
[uv]
owner = "astral-sh"
repo = "uv"
asset_name.linux = "_64-unknown-linux-gnu"
[ty]
owner = "astral-sh"
repo = "ty"
asset_name.linux = "_64-unknown-linux-gnu"
[watchexec]
owner = "watchexec"
repo = "watchexec"
asset_name.linux = "_64-unknown-linux-musl.t"
asset_name.windows = "zip"
[systemfd]
owner = "mitsuhiko"
repo = "systemfd"
asset_name.windows = "zip"
asset_name.linux = "musl"
[wild]
owner = "davidlattimore"
repo = "wild"
asset_name.linux = "r-x"
[mold]
owner = "rui314"
repo = "mold"
asset_name.linux = "_64-linux"
[probe-rs]
owner = "probe-rs"
repo = "probe-rs"
asset_name.linux = "probe-rs-tools-x86_64-unknown"
[minijinja-cli]
owner = "mitsuhiko"
repo = "minijinja"
exe_name = "minijinja-cli"
asset_name.linux = "_64-unknown-linux-gnu"
asset_name.windows = "zip"
[lychee]
owner = "lycheeverse"
repo = "lychee"
asset_name.linux = "_64-unknown-linux-gnu"
asset_name.windows = "exe"
[flyctl]
owner = "superfly"
repo = "flyctl"
asset_name.linux = "x_x"
asset_name.windows = "dows_x"
[static-curl]
owner = "stunnel"
repo = "static-curl"
exe_name = "curl"
asset_name.linux = "x-x86_64-m"
asset_name.windows = "ws-x86_64-8"
[hurl]
owner = "Orange-OpenSource"
repo = "hurl"
asset_name.linux = "_64-unknown-linux"
asset_name.windows = "msvc.zip"

# calculators
[rink]
owner = "tiffany352"
repo = "rink-rs"
exe_name = "rink"
asset_name.windows = "Win"
asset_name.linux = "Linux"
[numbat]
owner = "sharkdp"
repo = "numbat"
asset_name.linux = "_64-unknown-linux-g"
asset_name.windows = "_64-p"
[fend]
owner = "printfn"
repo = "fend"
asset_name.windows = "ws-x64-exe"
asset_name.linux = "_64-g"

# recorders
[satty]
owner = "gabm"
repo = "Satty"
exe_name = "satty"
asset_name.linux = "gz"
[micropad]
owner = "micropad"
repo = "MicroPad-Electron"
exe_name = "micropad"
asset_name.linux = "_64.AppImage"
[typst]
owner = "typst"
repo = "typst"
asset_name.linux = "_64-unknown-linux-musl"
asset_name.windows = "_64-pc-windows-msvc.zip"
[teams]
owner = "IsmaelMartinez"
repo = "teams-for-linux"
asset_name.linux = "4.A"
[yt-dlp] # -U
owner = "yt-dlp"
repo = "yt-dlp"
# asset_name.linux = "p$"
asset_name.windows = "p.exe"
[ruffle]
owner = "ruffle-rs"
repo = "ruffle"
asset_name.linux = "_64.tar"
asset_name.windows = "_64.zip"
[monolith]
owner = "Y2Z"
repo = "monolith"
asset_name.linux = "_64"
asset_name.windows = "exe"
