{
"proxy": "",
"tools": {
  "Dorion": {
    "asset_name": {
      "linux": "d64_portable",
      "windows": "n64_portable"
    },
    "owner": "SpikeHD",
    "repo": "Dorion"
  },
  "ast-grep": {
    "asset_name": {
      "linux": "_64-unknown-linux",
      "windows": "_64-p"
    },
    "owner": "ast-grep",
    "repo": "ast-grep"
  },
  "bandwhich": {
    "asset_name": {
      "linux": "_64-unknown-linux-m",
      "windows": "ws"
    },
    "owner": "imsnif",
    "repo": "bandwhich"
  },
  "bat": {},
  "binsider": {
    "asset_name": {
      "linux": "_64-unknown-linux-gnu",
      "windows": "windows"
    },
    "owner": "orhun",
    "repo": "binsider"
  },
  "bottom": {
    "asset_name": {
      "linux": "_64-unknown-linux-musl",
      "windows": "_64-pc-windows-msvc"
    },
    "exe_name": "btm",
    "owner": "ClementTsang",
    "repo": "bottom"
  },
  "broot": {
    "asset_name": {
      "windows": "zip"
    },
    "owner": "Canop",
    "repo": "broot"
  },
  "btdu": {
    "asset_name": {
      "linux": "_64"
    },
    "owner": "CyberShadow",
    "repo": "btdu"
  },
  "cargo-audit": {
    "asset_name": {
      "linux": "x-m"
    },
    "exe_name": "cargo-audit",
    "owner": "rustsec",
    "repo": "rustsec"
  },
  "cargo-dist": {
    "asset_name": {
      "linux": "_64-unknown-linux-musl",
      "windows": "_64-p"
    },
    "exe_name": "dist",
    "owner": "axodotdev",
    "repo": "cargo-dist"
  },
  "cargo-insta": {
    "asset_name": {
      "linux": "x-g"
    },
    "exe_name": "cargo-insta",
    "owner": "mitsuhiko",
    "repo": "insta"
  },
  "cargo-machete": {
    "asset_name": {
      "linux": "musl"
    },
    "owner": "bnjbvr",
    "repo": "cargo-machete"
  },
  "chdig": {
    "asset_name": {
      "linux": "t-x86_64.tar.g",
      "windows": "zip"
    },
    "owner": "azat",
    "repo": "chdig"
  },
  "cilium-cli": {
    "asset_name": {
      "linux": "linux-amd64"
    },
    "exe_name": "cilium",
    "owner": "cilium",
    "repo": "cilium-cli"
  },
  "comby": {
    "asset_name": {
      "linux": "tar"
    },
    "exe_name": "comby",
    "owner": "comby-tools",
    "repo": "comby"
  },
  "coreutils": {
    "asset_name": {
      "linux": "_64-unknown-linux-gnu",
      "windows": "_64-pc-windows-gnu.zip"
    },
    "owner": "uutils",
    "repo": "coreutils"
  },
  "crawl": {
    "asset_name": {
      "linux": "tiles.x"
    },
    "exe_name": "crawl-tiles",
    "owner": "crawl",
    "repo": "crawl"
  },
  "cyme": {
    "asset_name": {
      "linux": "_64-unknown",
      "windows": "ws"
    },
    "owner": "tuna-f1sh",
    "repo": "cyme"
  },
  "delta": {
    "asset_name": {
      "linux": "_64-unknown-linux-gnu",
      "windows": "_64-pc-windows-msvc"
    },
    "owner": "dandavison",
    "repo": "delta"
  },
  "difftastic": {},
  "diffutils": {
    "asset_name": {
      "linux": "_64-unknown-linux-gnu",
      "windows": "_64-pc-windows-gnu.zip"
    },
    "owner": "uutils",
    "repo": "diffutils"
  },
  "dprint": {
    "asset_name": {
      "linux": "_64-unknown-linux-gnu",
      "windows": "c.zip"
    },
    "owner": "dprint",
    "repo": "dprint"
  },
  "drivel": {
    "asset_name": {
      "linux": "_64-unknown-linux-gnu"
    },
    "owner": "hgrsd",
    "repo": "drivel"
  },
  "dua": {
    "asset_name": {
      "linux": "_64-unknown-linux-musl",
      "windows": "ws"
    },
    "exe_name": "dua",
    "owner": "Byron",
    "repo": "dua-cli"
  },
  "duckdb": {
    "asset_name": {
      "linux": "i-linux-amd64.z",
      "windows": "i-windows-am"
    },
    "owner": "duckdb",
    "repo": "duckdb"
  },
  "earthly": {
    "asset_name": {
      "linux": "linux-amd64"
    },
    "owner": "earthly",
    "repo": "earthly"
  },
  "eza": {
    "asset_name": {
      "linux": "_64-unknown-linux-musl.t"
    },
    "owner": "eza-community",
    "repo": "eza"
  },
  "fd": {},
  "fend": {
    "asset_name": {
      "linux": "_64-g",
      "windows": "ws-x64-exe"
    },
    "owner": "printfn",
    "repo": "fend"
  },
  "findutils": {
    "asset_name": {
      "linux": "x-g",
      "windows": "_64-pc-windows-gnu.zip"
    },
    "exe_name": "find",
    "owner": "uutils",
    "repo": "findutils"
  },
  "fish": {
    "asset_name": {
      "linux": "d64"
    },
    "exe_name": "fish",
    "owner": "fish-shell",
    "repo": "fish-shell"
  },
  "flamelens": {
    "asset_name": {
      "linux": "_64-unknown-linux-gnu",
      "windows": "zip"
    },
    "owner": "YS-L",
    "repo": "flamelens"
  },
  "flyctl": {
    "asset_name": {
      "linux": "x_x",
      "windows": "dows_x"
    },
    "owner": "superfly",
    "repo": "flyctl"
  },
  "fpcalc": {
    "asset_name": {
      "linux": "x-x",
      "windows": "ws-x"
    },
    "exe_name": "fpcalc",
    "owner": "acoustid",
    "repo": "chromaprint"
  },
  "fq": {
    "asset_name": {
      "linux": "x_amd",
      "windows": "ws"
    },
    "owner": "wader",
    "repo": "fq"
  },
  "gg": {
    "asset_name": {
      "linux": "App",
      "windows": "exe"
    },
    "owner": "gulbanana",
    "repo": "gg"
  },
  "gitleaks": {
    "asset_name": {
      "linux": "x_x64"
    },
    "owner": "gitleaks",
    "repo": "gitleaks"
  },
  "glance": {
    "asset_name": {
      "linux": "x-am",
      "windows": "s-am"
    },
    "owner": "glanceapp",
    "repo": "glance"
  },
  "gphotosdl": {
    "asset_name": {
      "linux": "x_x",
      "windows": "s_x"
    },
    "owner": "rclone",
    "repo": "gphotosdl"
  },
  "hextazy": {
    "asset_name": {
      "linux": "hextazy"
    },
    "owner": "0xfalafel",
    "repo": "hextazy"
  },
  "hexyl": {
    "asset_name": {
      "linux": "_64-unknown-linux-gnu",
      "windows": "_64-pc-windows-msvc.zip"
    },
    "owner": "sharkdp",
    "repo": "hexyl"
  },
  "hl": {
    "asset_name": {
      "linux": "_64-musl",
      "windows": "s.zip"
    },
    "owner": "pamburus",
    "repo": "hl"
  },
  "httm": {
    "asset_name": {
      "linux": "stripped"
    },
    "owner": "kimono-koans",
    "repo": "httm"
  },
  "hurl": {
    "asset_name": {
      "linux": "_64-unknown-linux",
      "windows": "msvc.zip"
    },
    "owner": "Orange-OpenSource",
    "repo": "hurl"
  },
  "hyperfine": {
    "asset_name": {
      "linux": "_64-unknown-linux-g",
      "windows": "_64-p"
    },
    "owner": "sharkdp",
    "repo": "hyperfine"
  },
  "imhex": {
    "asset_name": {
      "linux": "_64.A"
    },
    "owner": "WerWolv",
    "repo": "ImHex"
  },
  "jaq": {
    "asset_name": {
      "linux": "_64-unknown-linux-gnu",
      "windows": "_64-p"
    },
    "owner": "01mf02",
    "repo": "jaq"
  },
  "jj": {
    "asset_name": {
      "linux": "_64-unknown-linux-musl",
      "windows": "_64-pc-windows-msvc"
    },
    "owner": "jj-vcs",
    "repo": "jj"
  },
  "just": {
    "asset_name": {
      "linux": "_64-unknown-linux-musl",
      "windows": "_64-pc-windows-msvc"
    },
    "owner": "casey",
    "repo": "just"
  },
  "k9s": {},
  "kdash": {
    "asset_name": {
      "linux": "linux.tar"
    },
    "owner": "kdash-rs",
    "repo": "kdash"
  },
  "kdl-lsp": {
    "asset_name": {
      "linux": "_64-u",
      "windows": "_64-p"
    },
    "exe_name": "kdl-lsp",
    "owner": "kdl-org",
    "repo": "kdl-rs"
  },
  "krokiet": {
    "asset_name": {
      "linux": "t_gui_heif_libraw",
      "windows": "t.e"
    },
    "exe_name": "krokiet",
    "owner": "qarmin",
    "repo": "czkawka"
  },
  "kubetui": {
    "asset_name": {
      "linux": "_64-unknown-linux-musl"
    },
    "owner": "sarub0b0",
    "repo": "kubetui"
  },
  "lychee": {
    "asset_name": {
      "linux": "_64-unknown-linux-gnu",
      "windows": "exe"
    },
    "owner": "lycheeverse",
    "repo": "lychee"
  },
  "mdq": {
    "asset_name": {
      "linux": "u",
      "windows": "i"
    },
    "owner": "yshavit",
    "repo": "mdq"
  },
  "micropad": {
    "asset_name": {
      "linux": "_64.AppImage"
    },
    "exe_name": "micropad",
    "owner": "micropad",
    "repo": "MicroPad-Electron"
  },
  "minidump-stackwalk": {
    "exe_name": "minidump-stackwalk",
    "owner": "rust-minidump",
    "repo": "rust-minidump"
  },
  "minijinja-cli": {
    "asset_name": {
      "linux": "_64-unknown-linux-gnu",
      "windows": "zip"
    },
    "exe_name": "minijinja-cli",
    "owner": "mitsuhiko",
    "repo": "minijinja"
  },
  "mold": {
    "asset_name": {
      "linux": "_64-linux"
    },
    "owner": "rui314",
    "repo": "mold"
  },
  "monolith": {
    "asset_name": {
      "linux": "_64",
      "windows": "exe"
    },
    "owner": "Y2Z",
    "repo": "monolith"
  },
  "mprocs": {
    "asset_name": {
      "linux": "linux",
      "windows": "windows"
    },
    "owner": "pvolok",
    "repo": "mprocs"
  },
  "mpv-mpris2": {
    "asset_name": {
      "linux": "s"
    },
    "exe_name": "mpv-mpris2.so",
    "owner": "eNV25",
    "repo": "mpv-mpris2"
  },
  "netscanner": {
    "asset_name": {
      "linux": "_64"
    },
    "owner": "Chleba",
    "repo": "netscanner"
  },
  "nextest": {
    "asset_name": {
      "linux": "_64-unknown-linux",
      "windows": "_64-pc-windows-msvc.zip"
    },
    "exe_name": "cargo-nextest",
    "owner": "nextest-rs",
    "repo": "nextest"
  },
  "nu": {
    "asset_name": {
      "linux": "_64-unknown-linux-musl",
      "windows": "_64-pc-windows-msvc.zip"
    },
    "exe_name": "nu",
    "owner": "nushell",
    "repo": "nushell"
  },
  "numbat": {
    "asset_name": {
      "linux": "_64-unknown-linux-g",
      "windows": "_64-p"
    },
    "owner": "sharkdp",
    "repo": "numbat"
  },
  "offline-scrobbler": {
    "asset_name": {
      "linux": "x-m"
    },
    "owner": "theirix",
    "repo": "offline-scrobbler"
  },
  "oryx": {
    "asset_name": {
      "linux": "_64"
    },
    "owner": "pythops",
    "repo": "oryx"
  },
  "otel-cli": {
    "asset_name": {
      "linux": "x_amd64.t"
    },
    "owner": "equinix-labs",
    "repo": "otel-cli"
  },
  "picard": {
    "asset_name": {
      "windows": "d-2.13.2.e"
    },
    "owner": "metabrainz",
    "repo": "picard"
  },
  "probe-rs": {
    "asset_name": {
      "linux": "probe-rs-tools-x86_64-unknown"
    },
    "owner": "probe-rs",
    "repo": "probe-rs"
  },
  "processwatch": {
    "asset_name": {
      "linux": "w"
    },
    "owner": "intel",
    "repo": "processwatch"
  },
  "procs": {},
  "pwru": {
    "asset_name": {
      "linux": "d64"
    },
    "owner": "cilium",
    "repo": "pwru"
  },
  "quickwit": {
    "asset_name": {
      "linux": "_64-unknown-linux-gnu"
    },
    "owner": "quickwit-oss",
    "repo": "quickwit"
  },
  "rainfrog": {
    "asset_name": {
      "linux": "_64-unknown-linux-gnu",
      "windows": "_64-pc-windows-msvc.zip"
    },
    "owner": "achristmascarl",
    "repo": "rainfrog"
  },
  "rama": {
    "asset_name": {
      "linux": "_64-u"
    },
    "owner": "plabayo",
    "repo": "rama"
  },
  "rclone": {
    "asset_name": {
      "linux": "linux-amd64.zip",
      "windows": "windows-amd64"
    },
    "owner": "rclone",
    "repo": "rclone"
  },
  "recast": {
    "asset_name": {
      "linux": "_64-u",
      "windows": "_64-p"
    },
    "owner": "Altair-Bueno",
    "repo": "recast"
  },
  "rescrobbled": {
    "asset_name": {
      "linux": "s"
    },
    "owner": "InputUserName",
    "repo": "rescrobbled"
  },
  "rink": {
    "asset_name": {
      "linux": "Linux",
      "windows": "Win"
    },
    "exe_name": "rink",
    "owner": "tiffany352",
    "repo": "rink-rs"
  },
  "ripgrep": {},
  "ripgrep-all": {
    "asset_name": {
      "linux": "musl",
      "windows": "msvc"
    },
    "exe_name": "rga",
    "owner": "phiresky",
    "repo": "ripgrep-all"
  },
  "rsgain": {
    "asset_name": {
      "linux": "L",
      "windows": "win"
    },
    "owner": "complexlogic",
    "repo": "rsgain"
  },
  "ruffle": {
    "asset_name": {
      "linux": "_64.tar",
      "windows": "_64.zip"
    },
    "owner": "ruffle-rs",
    "repo": "ruffle"
  },
  "rustdesk": {
    "asset_name": {
      "linux": "_64.AppImage",
      "windows": "_64.exe"
    },
    "owner": "rustdesk",
    "repo": "rustdesk"
  },
  "rustscan": {
    "asset_name": {
      "linux": "_64-linux.zip",
      "windows": "exe"
    },
    "exe_name": "rustscan",
    "owner": "RustScan",
    "repo": "RustScan"
  },
  "satty": {
    "asset_name": {
      "linux": "gz"
    },
    "exe_name": "satty",
    "owner": "gabm",
    "repo": "Satty"
  },
  "sccache": {
    "asset_name": {
      "linux": "e-v0.9.1-x86_64-u",
      "windows": "e-v0.9.1-x86_64-p"
    },
    "owner": "mozilla",
    "repo": "sccache"
  },
  "shellcheck": {
    "asset_name": {
      "linux": "x.x",
      "windows": "zip"
    },
    "owner": "koalaman",
    "repo": "shellcheck"
  },
  "shfmt": {
    "asset_name": {
      "linux": "linux_amd64",
      "windows": "64.exe"
    },
    "owner": "patrickvane",
    "repo": "shfmt"
  },
  "shuttle": {
    "asset_name": {
      "linux": "_64-unknown-linux-gnu"
    },
    "owner": "shuttle-hq",
    "repo": "shuttle"
  },
  "srgn": {
    "asset_name": {
      "linux": "linux",
      "windows": "windows"
    },
    "owner": "alexpovel",
    "repo": "srgn"
  },
  "starship": {},
  "static-curl": {
    "asset_name": {
      "linux": "x-x86_64-m",
      "windows": "ws-x86_64-8"
    },
    "exe_name": "curl",
    "owner": "stunnel",
    "repo": "static-curl"
  },
  "store_directory": "$HOME/run",
  "systemfd": {
    "asset_name": {
      "linux": "musl",
      "windows": "zip"
    },
    "owner": "mitsuhiko",
    "repo": "systemfd"
  },
  "teams": {
    "asset_name": {
      "linux": ".8.A"
    },
    "owner": "IsmaelMartinez",
    "repo": "teams-for-linux"
  },
  "topgrade": {
    "asset_name": {
      "linux": "_64-unknown-linux-musl",
      "windows": "_64-pc-windows-msvc"
    },
    "owner": "topgrade-rs",
    "repo": "topgrade"
  },
  "trippy": {
    "asset_name": {
      "linux": "_64-unknown-linux-musl.tar",
      "windows": "_64-pc-windows-msvc"
    },
    "exe_name": "trip",
    "owner": "fujiapple852",
    "repo": "trippy"
  },
  "tspin": {
    "asset_name": {
      "linux": "_64-unknown-linux-musl"
    },
    "exe_name": "tspin",
    "owner": "bensadeh",
    "repo": "tailspin"
  },
  "typst": {
    "asset_name": {
      "linux": "_64-unknown-linux-musl",
      "windows": "_64-pc-windows-msvc.zip"
    },
    "owner": "typst",
    "repo": "typst"
  },
  "umoci": {
    "asset_name": {
      "linux": "d64"
    },
    "owner": "opencontainers",
    "repo": "umoci"
  },
  "uv": {
    "asset_name": {
      "linux": "_64-unknown-linux-gnu"
    },
    "owner": "astral-sh",
    "repo": "uv"
  },
  "watchexec": {
    "asset_name": {
      "linux": "_64-unknown-linux-musl.t",
      "windows": "zip"
    },
    "owner": "watchexec",
    "repo": "watchexec"
  },
  "wezterm": {
    "asset_name": {
      "linux": "-Ubuntu20.04.AppImage"
    },
    "owner": "wez",
    "repo": "wezterm"
  },
  "wild": {
    "asset_name": {
      "linux": "r-x"
    },
    "owner": "davidlattimore",
    "repo": "wild"
  },
  "xxhsum": {
    "asset_name": {
      "windows": "zip"
    },
    "owner": "Cyan4973",
    "repo": "xxHash"
  },
  "yt-dlp": {
    "asset_name": {
      "windows": "p.exe"
    },
    "owner": "yt-dlp",
    "repo": "yt-dlp"
  },
  "zellij": {
    "asset_name": {
      "linux": "_64-u"
    },
    "owner": "zellij-org",
    "repo": "zellij"
  }
}}
