# Installation directory for all the tools:
store_directory = "$HOME/run"

[rclone]
owner = "rclone"
repo = "rclone"
asset_name.linux = "linux-amd64.zip"
asset_name.windows = "windows-amd64"

# pagers
[bat]
[difftastic]
[starship]
[tspin]
owner = "bensadeh"
repo = "tailspin"
exe_name = "tspin"
asset_name.linux = "_64-unknown-linux-musl"
asset_name.windows = "_64-pc-windows-msvc"
[delta]
owner = "dandavison"
repo = "delta"
asset_name.linux = "_64-unknown-linux-gnu"
asset_name.windows = "_64-pc-windows-msvc"
[wezterm]
owner = "wez"
repo = "wezterm"
asset_name.linux = "-Ubuntu20.04.AppImage"
[coreutils]
owner = "uutils"
repo = "coreutils"
asset_name.linux = "_64-unknown-linux-gnu"
asset_name.windows = "_64-pc-windows-gnu.zip"
[findutils]
owner = "uutils"
repo = "findutils"
asset_name.linux = "_64-unknown-linux-gnu"
asset_name.windows = "_64-pc-windows-gnu.zip"
[diffutils]
owner = "uutils"
repo = "diffutils"
asset_name.linux = "_64-unknown-linux-gnu"
asset_name.windows = "_64-pc-windows-gnu.zip"
[nu]
owner = "nushell"
repo = "nushell"
exe_name = "nu"
asset_name.linux = "_64-unknown-linux-musl"
asset_name.windows = "_64-pc-windows-msvc.zip"
[hexyl]
owner = "sharkdp"
repo = "hexyl"
asset_name.linux = "_64-unknown-linux-gnu"
asset_name.windows = "_64-pc-windows-msvc.zip"
[hextazy]
owner = "0xfalafel"
repo = "hextazy"
asset_name.linux = "hextazy"
[imhex]
owner = "WerWolv"
repo = "ImHex"
asset_name.linux = "AppImage"
[binsider]
owner = "orhun"
repo = "binsider"
asset_name.linux = "_64-unknown-linux-gnu"
asset_name.windows = "windows"
[rustdesk]
owner = "rustdesk"
repo = "rustdesk"
asset_name.linux = "_64.AppImage"
asset_name.windows = "_64.exe"
[rainfrog]
owner = "achristmascarl"
repo = "rainfrog"
asset_name.linux = "_64-unknown-linux-gnu"
asset_name.windows = "_64-pc-windows-msvc.zip"

[crawl]
owner = "crawl"
repo = "crawl"
exe_name = "crawl-tiles"
asset_name.linux = "tiles.x"

# dashboards
[procs]
[btdu]
owner = "CyberShadow"
repo = "btdu"
asset_name.linux = "_64"
[broot]
owner = "Canop"
repo = "broot"
# asset_name.linux = "zip" # x86_64-linux/broot
asset_name.windows = "zip" # x86_64-pc-windows-gnu/broot.exe
[dua]
owner = "Byron"
repo = "dua-cli"
exe_name = "dua"
asset_name.linux = "_64-unknown-linux-musl"
asset_name.windows = "_64-pc-windows-msvc"
[trippy]
owner = "fujiapple852"
repo = "trippy"
exe_name = "trip"
asset_name.linux = "_64-unknown-linux-musl.tar"
asset_name.windows = "_64-pc-windows-msvc"
[rustscan]
owner = "RustScan"
repo = "RustScan"
exe_name = "rustscan"
asset_name.linux = "_64-linux.zip"
asset_name.windows = "exe"
[netscanner]
owner = "Chleba"
repo = "netscanner"
asset_name.linux = "_64"
[bandwhich]
owner = "imsnif"
repo = "bandwhich"
asset_name.linux = "musl"
[oryx]
owner = "pythops"
repo = "oryx"
asset_name.linux = "_64"
[bottom]
owner = "ClementTsang"
repo = "bottom"
exe_name = "btm"
asset_name.linux = "_64-unknown-linux-musl"
asset_name.windows = "_64-pc-windows-msvc"
[mprocs]
owner = "pvolok"
repo = "mprocs"
asset_name.windows = "windows"
asset_name.linux = "linux"
[cyme]
owner = "tuna-f1sh"
repo = "cyme"
asset_name.windows = "dows"
asset_name.linux = "_64-unknown"

# history wrangling
[just]
owner = "casey"
repo = "just"
asset_name.linux = "_64-unknown-linux-musl"
asset_name.windows = "_64-pc-windows-msvc"
[jj]
owner = "martinvonz"
repo = "jj"
asset_name.linux = "_64-unknown-linux-musl"
asset_name.windows = "_64-pc-windows-msvc"

# k8s
[k9s]
[kubetui]
owner = "sarub0b0"
repo = "kubetui"
asset_name.linux = "_64-unknown-linux-musl"
[kdash]
owner = "kdash-rs"
repo = "kdash"
asset_name.linux = "linux.tar"
[cilium-cli]
owner = "cilium"
repo = "cilium-cli"
exe_name = "cilium"
asset_name.linux = "linux-amd64"
# [helm]
# has checksums only
# owner = "helm"
# repo = "helm"
# asset_name.linux = "linux-amd64.tar"
[pwru]
owner = "cilium"
repo = "pwru"
asset_name.linux = "d64"

# search & destroy
[fd]
[ripgrep]
[comby]
owner = "comby-tools"
repo = "comby"
exe_name = "comby"
asset_name.linux = "tar"
[sg]
owner = "ast-grep"
repo = "ast-grep"
exe_name = "sg"
asset_name.linux = "_64-unknown-linux"
asset_name.windows = "_64-pc-windows"
[srgn]
owner = "alexpovel"
repo = "srgn"
asset_name.linux = "linux"
asset_name.windows = "windows"
[jaq]
owner = "01mf02"
repo = "jaq"
asset_name.linux = "_64-unknown-linux-gnu"
asset_name.windows = "windows-gnu"
[drivel]
owner = "hgrsd"
repo = "drivel"
asset_name.linux = "_64-unknown-linux-gnu"
[quickwit]
owner = "quickwit-oss"
repo = "quickwit"
asset_name.linux = "_64-unknown-linux-gnu"

# formatters
[dprint]
owner = "dprint"
repo = "dprint"
asset_name.linux = "_64-unknown-linux-gnu"
asset_name.windows = "_64-pc-windows-msvc"
[treefmt]
owner = "numtide"
repo = "treefmt"
asset_name.linux = "_64-unknown-linux-gnu"
asset_name.windows = "_64-pc-windows-msvc"
[rsgain]
owner = "complexlogic"
repo = "rsgain"
asset_name.linux = "nux.tar.xz"
asset_name.windows = "win"
[ruff]
owner = "astral-sh"
repo = "ruff"
asset_name.linux = "_64-unknown-linux-gnu"
[shellcheck]
owner = "koalaman"
repo = "shellcheck"
asset_name.windows = "zip"
[shfmt]
owner = "patrickvane"
repo = "shfmt"
asset_name.linux = "linux_amd64"
asset_name.windows = "64.exe"

# builders
[nextest]
owner = "nextest-rs"
repo = "nextest"
exe_name = "cargo-nextest"
asset_name.linux = "_64-unknown-linux"
asset_name.windows = "_64-pc-windows-msvc.zip"
[uv]
owner = "astral-sh"
repo = "uv"
asset_name.linux = "_64-unknown-linux-gnu"
[mold]
owner = "rui314"
repo = "mold"
asset_name.linux = "_64-linux"
[probe-rs]
owner = "probe-rs"
repo = "probe-rs"
asset_name.linux = "probe-rs-x86_64-unknown"

[lychee]
owner = "lycheeverse"
repo = "lychee"
asset_name.linux = "_64-unknown-linux-gnu"
asset_name.windows = "exe"
[flyctl]
owner = "superfly"
repo = "flyctl"
asset_name.linux = "x_x"
asset_name.windows = "dows_x"
[earthly]
owner = "earthly"
repo = "earthly"
asset_name.linux = "linux-amd64"
[hurl]
owner = "Orange-OpenSource"
repo = "hurl"
asset_name.linux = "_64-unknown-linux"
asset_name.windows = "msvc.zip"

# calculators
[rink]
owner = "tiffany352"
repo = "rink-rs"
exe_name = "rink"
asset_name.windows = "Win"
asset_name.linux = "Linux"
[fend]
owner = "printfn"
repo = "fend"
asset_name.windows = "windows-x64-exe"
asset_name.linux = "linux-x86_64"

# recorders
[satty]
owner = "gabm"
repo = "Satty"
exe_name = "satty"
asset_name.linux = "gz"
[micropad]
owner = "micropad"
repo = "MicroPad-Electron"
exe_name = "micropad"
asset_name.linux = "_64.AppImage"
[typst]
owner = "typst"
repo = "typst"
asset_name.linux = "_64-unknown-linux-musl"
asset_name.windows = "_64-pc-windows-msvc.zip"
[teams]
owner = "IsmaelMartinez"
repo = "teams-for-linux"
asset_name.linux = "11.0.AppImage"
[yt-dlp]
owner = "yt-dlp"
repo = "yt-dlp"
# asset_name.linux = "p$"
asset_name.windows = "p.exe"
[ruffle]
owner = "ruffle-rs"
repo = "ruffle"
asset_name.linux = "_64.tar"
asset_name.windows = "_64.zip"
[monolith]
owner = "Y2Z"
repo = "monolith"
asset_name.linux = "_64"
asset_name.windows = "exe"
