[misc]
assume_yes = true
no_retry = false
no_self_update = false
disable = [
  "brew_cask",
  "brew_formula",
  "cargo",
  "containers",
  "emacs",
  "firmware",
  "git_repos",
  "helm",
  "nix",
  "pip3",
  "rustup",
  "shell",
  "toolbx",
  "uv",
  "waydroid",
]
ignore_failures = ["distrobox", "flatpak", "home_manager"]

[linux]
rpm_ostree = true

[firmware]
upgrade = false
