[commands]
"cargo" = "cargo iu"
"sysext" = "run0 /usr/lib/systemd/systemd-sysupdate update -C emacs"

[misc]
sudo_command = "run0"
assume_yes = true
no_retry = false
no_self_update = false
disable = [
  "brew_cask",
  "brew_formula",
  "containers",
  "firmware",
  "helm",
  "nix",
  "pip3",
  "rustup",
  "cargo",
  "shell",
  "toolbx",
  "uv",
  "waydroid",
]
ignore_failures = []

[linux]
rpm_ostree = true

[firmware]
upgrade = false
