#!/bin/bash

# utils
alias g='git'
alias gp='g pr | grep "up to date" || g ml'
alias x=parallel
alias e="emacsclient -n"
alias f='firefox-nightly'
function yb() { f https:youtu.be/$1; }
function getc() {
    cd $1
    python2 $v/youtube-dl/youtube-dl || \
    python2 $v/youtube-dl/youtube-dl --batch-file dq.txt --output "%(upload_date)s-%(stitle)s-%(id)s.%(ext)s" || \
    curl --proxy socks4a://127.0.0.1:9050 $(cat tq.txt) || \
    wget --continue
}
alias nn='chrt -i 0 ionice -c 3 '

# places
if [[ $(hostname) == cenbaz ]]; then
    z=/cygdrive/c
    mount=/cygdrive/h
    roxer=/cygdrive/x
    pool=/cygdrive/m
else
    z=/mnt/cenbaz
    mount=~
    roxer=/mnt/roxer
    pool=/mnt/marbi
fi
h=$mount/Public/hdhoang
conf=$h/system-config/$(hostname)
t=$mount/t
dl=$mount/Downloads
m=$mount/Music
p=$mount/Pictures
v=$mount/Videos
mi=$mount/Public/mirror
g=$z/@g
s=$z/@s
pkg=/var/cache/pacman/pkg

fav=$mount/Public/fav
fm=$fav/Music

# local info
alias ls='ls --color=auto --file-type --group-directories-first'
alias df='df -hT --total -x tmpfs -x devtmpfs -x rootfs'
alias du='du -h --total'
alias dumx='dumx -h -xdev'
alias locate='locate -ie'
alias p='pgrep -f'
alias s='watch "cpupower -c all frequency-info -mf; cpupower -c all frequency-info -ms; grep current /sys/kernel/debug/dri/0/radeon_pm_info; sensors | grep -v fan"'
alias fr='free -m'
alias t='tail -f'

# network info
alias nh='sudo nethogs'
alias np='sudo tcpdump -w - | pv -bert >/dev/null'
port_mapping=(
587 tcp 465 tcp # tor
588 tcp 466 tcp # tor
25 tcp # exim
80 tcp 443 tcp # lighttpd
)
alias op='upnpc -r ${port_mapping[*]} && upnpc -a 192.168.0.56 22 2222 tcp'

# file ops
alias mkdir='mkdir -p'
alias cp='cp -r --reflink=auto --preserve=xattr'
alias ln='ln -i'
alias mv='mv -i'
alias rm='rm --interactive=once --one-file-system'
alias prv='perl-rename -iv'
alias rs='nn rsync --human-readable --verbose --progress --partial --archive'
alias bu='rs --delete --exclude=sumatrapdfcache/ --exclude=emacs-prelude/ $z/@{s,g} $mount/s $h $mount/secrets $p $mount/Public/pic $mi/{book,p} $m $v $pool'

# system
alias ssc='sudo systemctl --system'
alias usc='systemctl --user'

alias mp='nn makepkg -isf'
alias i='sudo pacman'
alias pc='pacman -Qdt && i -R $(pacman -Qdtq)'
alias cower='cower -fddt $ap'
ap=~/archlinux
function aur {
    cd $ap
    cower $1 || curl https://aur.archlinux.org/packages/$1/$1.tar.gz | tar zxv
    cd $1
    mp ${*:2}
}

# fun
alias c="crawl-tiles&"
alias m='mplayer'
alias mi=mediainfo
alias ti=gtorrentviewer
alias dum='dumx -v $m -type d|cut -c 9-|x -kX ls -1'
alias favd='ls $fm/*/* | grep -o "[^/]*_@_[^[]*" | uniq -di'
alias fava='ls $fm/*/* | grep -o "[^/]*_@" | uniq -c | sort -n'
alias favl='ls $fm/*/* | grep -o "\[.*\]" | sort | uniq -c | sort -n'
alias favs='rs --delete $fav $pool'
function favm() {
    # not using alias to keep emacs hili sane
    cd $fm
    prv "tr/ /_/;
         s/^''/_/; s/''/-/g;
         tr/\"*:<>/-/; s/\?//g;
         s/_\[Unknown_Album\]//i;
         s/\[unknown\]/(unknown)/;
         s/\[dialogue\]/(dialogue)/;
         s/\[untitled\]/(untitled)/" *
}
