---
- name: media packages
  package:
    name: "{{ item }}"
  with_items:
    - minidlna
- name: minidlna ports
  firewalld:
    permanent: yes
    immediate: yes
    state: enabled
    zone: internal
    service: minidlna
- name: minidlna.conf
  copy:
    dest: /etc/minidlna.conf
    content: |
      friendly_name={{ ansible_hostname }}
      port=8200
      user=minidlna
      media_dir={{ public }}
      media_dir={{ home }}/phim
      media_dir={{ home }}/Sync
      merge_media_dirs=yes
      force_sort_criteria=+dc:date
- name: allow minidlna to read home
  file:
    state: directory
    path: /etc/systemd/system/minidlna.service.d/
- copy:
    dest: /etc/systemd/system/minidlna.service.d/override.conf
    content: |
      [Service]
      ProtectHome=read-only
- systemd: daemon_reload=yes name=minidlna state=started enabled=yes
...
