---
- name: commandline packages
  become: yes
  package:
    name: "{{ item }}"
  with_items:
    - android-tools
    - android-udev
    - ansible
    - emacs
    - fish
    - git
    - inotify-tools
    - jq
    - lsof
    - p7zip
    - pkgfile
    - python2-systemd
    - smartmontools
    - sshpass
    - strace
    - ltrace
    - rsync
    - rustup
    - sysdig
    - time
    - tmux
    - tree
    - vim
    - wget
    - youtube-dl
    - phantomjs
    - expac
    - yajl
- name: user hdhoang
  become: yes
  user:
    name: hdhoang
    uid: 1000
    group: users
    groups: [ wheel, systemd-journal, log, video, audio, uucp, adbusers ]
    append: yes
    shell: /usr/bin/fish
    ssh_key_type: ed25519
    generate_ssh_key: yes

- systemd: daemon_reload=yes user=yes state=started enabled=yes name="{{ item }}"
  with_items:
    - gpg-agent.socket
    - gpg-agent-ssh.socket

- name: environment
  copy:
    dest: "{{ home }}/.pam_environment"
    content: |
      DBUS_SESSION_BUS_ADDRESS DEFAULT=unix:path=/run/user/1000/bus
      SSH_AUTH_SOCK=/run/user/1000/gnupg/S.gpg-agent.ssh
      ANSIBLE_VAULT_PASSWORD_FILE DEFAULT=@{HOME}/.ansible/vault_password
      PATH DEFAULT=@{HOME}/bin:@{HOME}/.cargo/bin:/bin
      LD_LIBRARY_PATH DEFAULT=@{HOME}/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib:@{HOME}/.rustup/toolchains/nightly-armv7-unknown-linux-gnueabihf/lib
      ALTERNATE_EDITOR DEFAULT=emacs
      VISUAL DEFAULT=emacsclient
      EDITOR DEFAULT=emacsclient
      BROWSER DEFAULT=firefox-nightly
      TERMINAL DEFAULT=alacritty
      RUST_BACKTRACE DEFAULT=full

- name: directories
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{ home }}/bin/"
    - "{{ home }}/Downloads/"
    - "{{ config_dir }}/fish/conf.d/"
    - "{{ config_dir }}/fish/functions/"
    - "{{ config_dir }}/systemd/user/"
    - "{{ config_dir }}/mpv/"
    - "{{ config_dir }}/youtube-dl/"
- get_url:
    url: https://github.com/jichu4n/fish-command-timer/raw/master/conf.d/fish_command_timer.fish
    dest: "{{ config_dir }}/fish/conf.d/"

- name: ansible.cfg
  ini_file:
    path: "{{ home }}/.ansible.cfg"
    section: defaults
    option: inventory
    value: "{{ home }}/Sync/machines/inventory.ini"

- name: vimrc
  copy:
    dest: "{{ home }}/.vimrc"
    content: set mouse=r

- name: youtube-dl config
  copy:
    dest: "{{ config_dir }}/youtube-dl/config"
    content: |
      --format "[height <=? 480]"
      --youtube-skip-dash-manifest
      --download-archive "{{ public }}/Videos/download-archive"
      --output "{{ public }}/Videos/%(uploader)s %(upload_date)s %(title)s@%(id)s.%(ext)s"

- name: tmux.conf
  copy:
    dest: "{{ home }}/.tmux.conf"
    content: |
      set -g base-index 1
      set -g pane-base-index 1
      set -g history-limit 10000
      set-window-option -g mode-keys vi
      set-window-option -g aggressive-resize on
- name: tmux.service
  copy:
    dest: "{{ config_dir }}/systemd/user/tmux.service"
    content: |
      [Install]
      WantedBy=default.target
      [Unit]
      Description=tmux default session (detached)
      Documentation=man:tmux(1)

      [Service]
      Type=forking
      Restart=always
      ExecStart=/usr/bin/tmux new-session -ADd -n journal journalctl -f
      ExecStop=/usr/bin/tmux kill-server
      Environment=DISPLAY=:0
      KillMode=none
- systemd: daemon_reload=yes user=yes name=tmux enabled=yes state=started

- name: install rust
  shell: "rustup toolchain add stable && rustup component add rust-src rust-analysis rls-preview --toolchain stable"

- name: AUR
  file:
    state: directory
    path: "{{ pacaur }}/"
- name: AUR keys
  command: gpg --recv-keys 1eb2638ff56c0c53 bbbebdbb24c6f355 b0f4253373f8f6f510d42178520a9993a1c052f8
- name: AUR packages
  git:
    repo: https://aur.archlinux.org/{{ item }}.git
    dest: "{{ pacaur }}/{{ item }}"
    # armv7h machines often patch PKGBUILD
    force: yes
  with_items:
    - cower
    - pacaur
    - firefox-nightly
    - heroku-cli
    - netatop-dkms
...
