app = "delicate-firefly-5184"
primary_region = "sin"

[http_service]
internal_port = 1200
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[env]
IG_USERNAME = "old.zeratul"
TZ = "Asia/Phnom_Penh"
TIMEZONE = "Asia/Phnom_Penh"
