[package]
name = "artlist"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
knus = { git = "https://github.com/thelostlambda/knus", default-features = false, features = ["derive", "line-numbers"] }
miette = { version = "7", default-features = false, features = ["fancy"] }
url = { version = "2", default-features = false }
