- lineinfile: dest=/etc/sudoers line="%wheel ALL = (ALL) ALL" validate="visudo -c -f %s"
- file: state=link src=../usr/share/zoneinfo/Asia/Ho_Chi_Minh path=/etc/localtime
- lineinfile: dest=/etc/locale.gen line="{{locale}}.UTF-8 UTF-8"
- lineinfile: dest=/etc/locale.conf line="LANG={{locale}}.UTF-8"
- command: locale-gen creates=/usr/lib/locale/locale-archive
- copy: src=caps2ctrl.map dest=/usr/share/kbd/keymaps/
- copy: dest=/etc/vconsole.conf content="KEYMAP=caps2ctrl"
- template: src=hosts dest=/etc/
- group: name={{user}} gid=1000
- user: name={{user}} uid=1000 createhome=no group={{user}} groups=wheel,systemd-journal,uucp shell=/bin/zsh
- name: pacman mirror
  lineinfile: dest=/etc/pacman.d/mirrorlist insertbefore=BOF line="Server = http://f.archlinuxvn.org/archlinux/$repo/os/$arch"
  when: ansible_architecture != "armv7l"
- lineinfile: dest=/etc/pacman.d/mirrorlist insertbefore=BOF line="Server = http://vn.mirror.archlinuxarm.org/$arch/$repo"
  when: ansible_architecture == "armv7l"
- ini_file: dest=/etc/pacman.conf section=multilib option=Include value=/etc/pacman.d/mirrorlist
  when: ansible_architecture == "x86_64"
- ini_file: dest=/etc/pacman.conf section=blackarch option=Server value=http://f.archlinuxvn.org/$repo/$repo/os/$arch
- lineinfile: dest=/etc/pacman.conf line={{item}} insertafter=options
  with_items:
    - UseSyslog
    - Color
    - VerbosePkgLists
# - command: pacman-key -r 7533bafe69a25079
# - command: pacman-key --lsign 7533bafe69a25079
- lineinfile: dest=/etc/makepkg.conf line='MAKEFLAGS="-j{{ansible_processor_vcpus}}"'
- pacman: state=absent name={{item}}
  with_items:
    - jfsutils
    - lvm2
    - nano
    - mdadm
    - netctl
    - reiserfsprogs
    - dhcpcd
    - xfsprogs
- name: utils
  pacman: name={{item}}
  with_items:
    - android-tools
    - dosfstools
    - ethtool
    - git
    - haveged
    - iotop
    - lm_sensors
    - mlocate
    - net-tools
    - ntfs-3g
    - openssh
    - openvpn
    - p7zip
    - parallel
    - pkgfile
    - pv
    - sshpass
    - sysdig
    - tcpdump
    - traceroute
    - tree
    - uucp
    - vim
    - wget
    - yaourt
    - zsh
- name: pkgfile update
  command: pkgfile -u creates=/var/cache/pkgfile/core.files
- service: name=haveged state=started enabled=yes
- name: SSD scheduler
  copy: dest=/etc/udev/rules.d/60-ssd-scheduler.rules content='ACTION=="add|change", KERNEL=="sd[a-z]", ATTR{queue/rotational}=="0", ATTR{queue/scheduler}="noop"'
